# RDS-delete.yaml

---
- name: Delete RDS instance
  hosts: localhost
  connection: local
  collections:
    - amazon.aws

  tasks:
    - name: Delete RDS instance
      amazon.aws.rds_instance:
        state: absent
        db_instance_identifier: "my-rds"
        region: "us-east-1"
        skip_final_snapshot: true
    - name: RDS deleted confirmation
      debug:
        msg: "RDS instance my-rds deleted!"